config/routes.rb
Rails.application.routes.draw do
  get 'tips_lists/new'
  get 'tips_lists/create'
  devise_for :users
  root to: 'pages#home'

  get "guests", to: "shares#index"
  get "guests/invite", to: "shares#new_guest"
  post "guests", to: "shares#invite_guest"
  get "guests/show", to: "shares#show"
  get "guests/share", to: "shares#share_list"
  get "guests/invite/url", to: "shares#invite_url"
  get "get_inspired", to: "tips#all_tips"
  get "get_inspired/new", to: "tips#add_to_list"


  resources :lists, only: [:index, :new, :create, :show] do
    resources :tips_lists, only: [:new, :create, :show]
  end

  resources :tips, only: [:new, :create]

  resources :tips, only: [:index, :show]
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_tips
  has_many :shares
  has_many :property_lists
  has_many :tips, through: :list_tips
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user

    if @list.save
      redirect_to list_path(@list) # redirecting to index
    else
      render :new
    end
  end

  def index
    @lists = List.where(user_id: current_user.id)
    @shares = Share.where(user_id: current_user.id)
  end

  def show
    @list = List.find(params[:id])
    @list_tips = ListTip.where(list_id: @list.id)
    @markers = @list_tips.map do |list_tip|
      {
        lat: list_tip.tip.latitude,
        lng: list_tip.tip.longitude
      }
    end
    @list_tips = ListTip.where(list_id: @list.id)

  end

  def edit
  end

  def update
  end

  def delete
  end

private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/views/lists/index.html.erb
<div class="web-container">

  <div class="d-flex" style="margin-bottom: -8px;">
    <h1 class="logotype">Boost-it</h1>
      <div class="settings" style="margin-top: 0px;">
        <%if user_signed_in? == true %>
          <li class="nav-item dropdown">
            <%= image_tag "settings.png", class: "settings dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                 <% else %>
                <% end %>
              </div>
          </li>
      </div>
  </div>


    <div class="title and subtitle">
      <h1>Welcome <%=current_user.first_name%></h1>
      <br>
      <p id="p-centered">Add new lists to share with your guests</p>
    </div>
    <div class="button-container">
      <%= link_to "NEW LIST", new_list_path, class:"add-button" %>
    </div>
    <br>
    <div class="d-flex justify-content-center">
      <div class ="active tabs" id="user-lists">Your Lists
      </div>
      <div id="shared-lists" class="tabs">Shared
      </div>
    </div>

  <div class="user-lists">
    <%= link_to tips_path do%>
      <div class="card-container">
        <div class="list-card" id="list-card" style="height:125px; margin-top: 20px; text-align: center; background-image: linear-gradient(rgba(90, 1, 54, 0.9), rgba(90, 1, 54, 0.9)), url(https://source.unsplash.com/random?restaurant);">
          <h2>All Tips</h2>
        </div>
      </div>
    <% end %>

    <% @lists.each do |list| %>
      <%= link_to list_path(list.id) do%>
        <div class="card-container">
          <% if(list.tips.sample) %>
            <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(
              <% if list.tips.last.photo.present? %>
                <%= list.tips.last.photo %>);">
              <% else %>
               <%= list.tips.last.google_pic %>);">
              <%end%>
              <h2> <%= list.name %> </h2>
            </div>
          <% else %>
            <div class="list-card">
              <h2> <%= list.name %> </h2>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="shared-lists">
    <% if (@shares.empty?) %>
      <p>You don't have any shared lists</p>
    <% else %>
        <% @shares.each do |share| %>
          <%= link_to list_path(List.find(share.list_id)) do%>
            <div class="card-container">
              <% if(share.list.tips.first) %>
                <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(
                  <% if list.tips.last.photo.present? %>
                    <%= List.find(share.list_id).tips.last.photo %>);">
                  <% else %>
                    <%= List.find(share.list_id).tips.last.google_pic %>;">
                  <%end%>
                  <div style="text-align: center;">
                    <h2> <%= share.list.name %> </h2>
                    <p2> Shared by <%= User.find(share.list.user_id).first_name %> </p2>
                  </div>
                </div>
              <% else %>
                <div class="list-card">
                  <div style="text-align: center;">
                    <h2> <%= share.list.name %> </h2>
                    <p2> Shared by <%= User.find(share.list.user_id).first_name %> </p2>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="web-container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col md-4">
      <h2 class="text-center">Create Your List</h2>
        <%= simple_form_for(@list) do |c| %> <!-- this is the action that tells the button submit where to -->
          <div class="form-inputs col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
            <%= c.input :name %>
            <div class="d-flex justify-content-between align-items-center" style="margin-top: -30px">
              <%= link_to "Cancel", lists_path, class: "mr-5 ml-3"%>
            <%= c.button :submit, "SAVE", class: "add-button" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="web-container">
  <div class="d-flex justify-content-between">
    <%= link_to lists_path do %>
      <i class="fas fa-chevron-left" style="color: black; font-size: 1.3rem;"></i>
    <% end %>
    <i id="toogle-map-lists-show" class="fas fa-map-marked-alt" style="color: black; margin-top: 2px;"></i>
  </div>
  <h1> <%= @list.name %> </h1>
  <br>
  <p id="p-centered">Add your favourite places to the list</p>
  <div class="button-container">
    <%= link_to "CREATE TIP", new_list_tips_list_path(@list), class:"add-button" %>
  </div>
  <div class="tips-index-links relative" id="lists-show-index-cards">
    <% @list_tips.each do |list_tip| %>

      <%= link_to "", tip_path(list_tip.tip), class:"absolute-0-0"%>
        <div class="d-flex justify-content-between align-items-center mt-3 pt-3 mb-0">
          <h2 class="mb-2">
            <%=  list_tip.tip.title %>
          </h2>
        </div>
        <div class="d-flex mt-0 mb-3">
          <img class="avatar-show-page" alt="avatar-large" style="margin-top: 12px;"src="https://avatars2.githubusercontent.com/u/55089715?v=4" />
          <div class="title-desc" style="margin-top: 10px;">
            <p>
              <% if list_tip.tip.review.length <= 83 %>
                <%=  list_tip.tip.review[0, 83] %>
              <% else %>
                <%=  list_tip.tip.review[0, 83] %> ...
              <% end %>
            </p>
          </div>
        </div>
        <div class="d-flex justify-content-center align-items-center" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(
          <% if list_tip.tip.photo.present? %>
            <%= cl_image_path list_tip.tip.photo %>
          <% else %>
            <%= cl_image_path list_tip.tip.google_pic if list_tip.tip.google_pic %>
          <%end%>); height: 200px; background-size: cover; border-radius: 5px;">
          <btn class="pill-category-tips-index <%= Tip::COLORS[list_tip.tip.category.to_sym] %>">
            <%=  list_tip.tip.category %>
          </btn>
        </div>
        <p class="address-tips-index mt-2" style="font-size: 16px">
          <%=  list_tip.tip.address %>
        </p>
    <% end %>
  </div>
  <div id="location-div-lists-show" class="d-none">
    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>