config/routes.rb
Rails.application.routes.draw do
  get 'tips_lists/new'
  get 'tips_lists/create'
  devise_for :users
  root to: 'pages#home'

  get "guests", to: "shares#index"
  get "guests/invite", to: "shares#new_guest"
  post "guests", to: "shares#invite_guest"
  get "guests/show", to: "shares#show"
  get "guests/share", to: "shares#share_list"
  get "guests/invite/url", to: "shares#invite_url"
  get "get_inspired", to: "tips#all_tips"
  get "get_inspired/new", to: "tips#add_to_list"


  resources :lists, only: [:index, :new, :create, :show] do
    resources :tips_lists, only: [:new, :create, :show]
  end

  resources :tips, only: [:new, :create]

  resources :tips, only: [:index, :show]
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def index
    @guests = Share.all
    @guests_filtered = []
    @lists = current_user.lists
    @guests_lists_count = []

    @guests.each do |guest|
      if List.find(guest.list_id).user_id == current_user.id
        if @guests_filtered.exclude?(guest.user_id)
          @guests_filtered << guest.user_id
        end
      end
    end

    @guests_filtered.each do |g_id|
      guest_lists = []
      User.find(g_id).shares.map(&:list_id).each do |list|
        if List.find(list).user_id == current_user.id
          guest_lists << list
        end
      end
    @guests_lists_count << guest_lists.length
    end
  end


  def new_guest
    @guest = User.new
  end

  def invite_url
  end

  def invite_guest
    # skip auto-mailer from devise
    new_guest = User.invite!(user_params) do |u|
      u.skip_invitation = true
    end
    token = new_guest.raw_invitation_token
    # adding devise invite token as instance attribute, for every environment
    if Rails.env.production?
      new_guest.invite_url = "http://boostit.herokuapp.com/users/invitation/accept?invitation_token=#{token}"
    else
      new_guest.invite_url = "http://localhost:3000/users/invitation/accept?invitation_token=#{token}"
    end
    new_guest.save!
    # create a share instance (list and user)
    params[:lists_id].each do |list_id|
      Share.create(user_id: new_guest.id, list_id: list_id)
    end
    # calling mailer method welcome to create view and deliver e-mail
    UserMailer.with(user: new_guest).welcome.deliver_now
    redirect_to guests_invite_url_path(id: new_guest.id)
  end

  def share_list
    share_list = List.find(params[:list_id])
    share_user_guest = User.find(params[:guest_user_id])
    Share.create(user_id: share_user_guest.id, list_id: share_list.id)
    if params[:path] == "add"
      redirect_to guests_show_path(guest_user_id: params[:guest_user_id])
    else
      redirect_to guests_path
    end
  end

  def show
    @guest = User.find(params[:guest_user_id])

    @lists = current_user.lists
    @shared_lists = Share.where(user_id: @guest.id).map(&:list_id).map do |list_id|
      List.find(list_id)
    end

    @unshared_lists = []

    @lists.each do |to_share_list|
      if @shared_lists.exclude?(to_share_list)
        @unshared_lists << to_share_list
      end
    end

    @guest_lists = @shared_lists.length
    @guest_tips = 0
    @shared_lists.each do |list|
      if list.user_id == current_user.id
        @guest_tips += list.tips.length
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name)
  end
end

app/views/shares/index.html.erb
<div class="web-container">
  <h1 style="margin-top: 45px;">Your Guests</h1> <br>
  <p id="p-centered" style="margin-bottom: -2px;">Share your lists with your guests</p>
  <div class="button-container">
    <%= link_to "ADD GUEST", guests_invite_path, class:"add-button" %>
  </div>
  <div class="user-lists">
    <% counter = 0 %>
    <% @guests_filtered.each do |guest| %>
      <%= link_to guests_show_path({guest_user_id: guest}) do%>
        <div class="guest-card d-flex justify-content-between" style="margin-bottom: 15px;" style="margin-bottom: 15px;">
          <div class="name-mail-date">
            <p class="guest-name" style="text-align: left; font-size: 22px;"><strong><%= "#{User.find(guest).first_name}"%></strong></p>
            <% if User.find(guest).email.length <= 20   %>
              <p class="guest-mail" style="font-size: 16px;"><%="#{User.find(guest).email}" %></p>
              <% else %>

              <p class="guest-mail" style="font-size: 16px;"><%="#{User.find(guest).email[0, 15]}" %>...</p>

            <% end %>
            <p class="guest-since" style="font-size: 16px;">Guest since <%= Date.parse("#{User.find(guest).created_at}").strftime("%d/%m/%Y")%></p>
          </div>
          <div class= "d-flex p-1">
            <div class="lists-shared">
              <p class="number-of-lists" style="text-align: center; font-size: 21px;"><%= @guests_lists_count[counter] %></p>
              <% if @guests_lists_count[counter] == 1 %>
                <p style="text-align: center; font-size: 16px;"> list shared </p>
              <% else %>
                <p style="text-align: center; font-size: 16px;"> lists shared </p>
              <% end %>
            </div>
              <% counter += 1 %>
            <p style="padding-top: 20px; padding-left: 21px;">></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shares/invite_url.html.erb
<div class="web-container">
  <div class="d-flex">
    <a href="#">
      <%= link_to guests_path do %>
      <i class="fas fa-chevron-left" style="color: black; font-size: 1.3rem;"></i>
      <% end %>
    </a>
  </div>
  <br>
  <h1>Congratulations!</h1>
  <br>
  <p>An email with the invitation link has been sent to <%=User.find(params[:id]).first_name %>.</p>
  <br>
  <h2>Share through other media</h2>
  <div class="share-module">
    <div class="link-to-share" style="font-size: 18px;">
      <p style="margin: 0px;">Hi <%=User.find(params[:id]).first_name %>,</p>
      <p> I want to share with you my best tips from the city, in order to see them, just click in the following link:
      <%= link_to "start now!", User.find(params[:id]).invite_url, class: "invite-link", id: "my-input" %>
    </div>
      <div class="d-flex justify-content-between align-items-center" style="margin-top: -30px; padding-right: 17px; padding-left: 32px;">
        <div id="copy-link-button">
          <button style="color: black;">Copy link</button>
        </div>
        <%= link_to "CONTINUE", guests_show_path(guest_user_id: params[:id]), class:"add-button" %>
      </div>
  </div>
  <div style="text-indent: -1000em;">
    <input type="text" value="Hi <%=User.find(params[:id]).first_name %>, I want to share with you my best tips from the city, in order to see them, just click in the following link: <%= User.find(params[:id]).invite_url %>" id="my-input-dos">
  </div>
</div>

app/views/shares/new_guest.html.erb
<div class="web-container">
 <div class="row justify-content-center">
    <div class="col-xs-12 col md-4">
      <h2 class="text-center">Email Your Guest</h2>
      <%= simple_form_for(@guest, url: guests_path(@guest), method: :post) do |c| %> <!-- this is the action that tells the button submit where to -->
        <div class="form-inputs col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
          <%= c.input :first_name, label: "Your guest's name" %>
          <%= c.input :email %>
          <% counter = 1 %>
          <% current_user.lists.each do |list| %>
            <input type="checkbox" name="lists_id[]" id="<%= list.id %>" value="<%= list.id %>"> <%= list.name %> <br>
            <% counter +=1 %>
          <% end %>
          <div class="d-flex justify-content-between align-items-center" style="margin-top: -30px">
            <%= link_to "Cancel", guests_path, class: "mr-5 ml-3"%>
            <%= c.button :submit, "SEND", class: "add-button" %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
 </div>

app/views/shares/show.html.erb
<div class="web-container">
  <div class="d-flex">
    <a href="#">
      <%= link_to guests_path do %>
        <i class="fas fa-chevron-left" style="color: black; font-size: 1.3rem;"></i>
      <% end %>
    </a>
  </div>
  <br>

  <h1 class="mb-3">Shared with <%= @guest.first_name %></h1>

  <%# count lists and tips for guest%>
  <div class="d-flex justify-content-around lists-tips mt-3">
    <div class="lists-shared">
      <p class="number-of-lists" style="margin-bottom: 5px;text-align: center; font-size: 22px;"><%= @guest_lists %></p>
      <p>Lists shared</p>
    </div>
    <div class="lists-shared">
      <p class="number-of-lists" style="margin-bottom: 5px; text-align: center; font-size: 22px;"><%= @guest_tips %></p>
      <p>Tips shared</p>
    </div>
  </div>


  <% if @unshared_lists.length != 0 %>
    <br>
    <p>Share an additional list?</p>
  <% end %>

  <% @unshared_lists.each do |list| %>
      <%= link_to guests_share_path({list_id: list.id, guest_user_id: @guest.id, path: "add"}) do%>
  <div class="card-container">
    <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(
              <% if list.tips.present? && list.tips.last.photo.present? %>
                <%= list.tips.last.photo %>
              <% elsif list.tips.present? %>
               <%= list.tips.last.google_pic %>
              <%end%>);">
      <p style="text-align: center"><%= "#{list.name}"%>
    </div>
  </div>
      <% end %>

    <% end %>
  <br>
  <h2>Shared lists</h2>
  <% @shared_lists.each do |list| %>
  <div class="card-container">
    <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<% if list.tips.present? && list.tips.last.photo.present? %>
                <%= list.tips.last.photo %>)
              <% elsif list.tips.present? %>
               <%= list.tips.last.google_pic %>
              <%end%>);">
      <p style="text-align: center"><%= "#{list.name}"%>
    </div>
  </div>
    <% end %>
</div>