config/routes.rb
Rails.application.routes.draw do
  get 'tips_lists/new'
  get 'tips_lists/create'
  devise_for :users
  root to: 'pages#home'

  get "guests", to: "shares#index"
  get "guests/invite", to: "shares#new_guest"
  post "guests", to: "shares#invite_guest"
  get "guests/show", to: "shares#show"
  get "guests/share", to: "shares#share_list"
  get "guests/invite/url", to: "shares#invite_url"
  get "get_inspired", to: "tips#all_tips"
  get "get_inspired/new", to: "tips#add_to_list"


  resources :lists, only: [:index, :new, :create, :show] do
    resources :tips_lists, only: [:new, :create, :show]
  end

  resources :tips, only: [:new, :create]

  resources :tips, only: [:index, :show]
end

app/controllers/tips_lists_controller.rb
class TipsListsController < ApplicationController
  def new
    # grab list
    @list = List.find(params[:list_id])
    @list_tip = ListTip.new
    # give selection of all lists
    # pass as hidden field to create
  end

  def create
    @tip = Tip.find_or_create_by(title: params[:tip][:title])
    @tip.address = params[:tip][:address]
    @tip.review = params[:tip][:review]
    @tip.category = params[:tip][:category]
    @tip.photo = params[:tip][:photo]
    @tip.google_pic = params[:tip][:google_pic]
    @tip.user = current_user
    @tip.save!
    @tip_list = ListTip.new
    @tip_list.tip = @tip
    @tip_list.list = List.find(params[:list_id])
    @list = List.find(params[:list_id])
    @tip_list.save!
    redirect_to list_path(@list)
  end

  def show
    # @list_tip = ListTip.geocoded # returns Tip with coordinates
    @list_tip = ListTip.find(params[:id])
    # @markers = [{
      # lat: @list_tip.latitude,
      # lng: @list_tip.longitude
    # }]
  end



 #    @tip = Tip.new(tip_params)
 #    @tip.user = current_user
 #    @list = List.find(params[:list_id])

 #    if @tip.save
 #      TipsLists.create(tip_id: @tip.id, list_id: @list.id)
 #      redirect_to lists_path # redirecting to lists
 #    else
 #      render :new
 #    end
 #  end



 # @restaurant = Restaurant.find(params[:restaurant_id])
 #    @review = Review.new(review_params)
 #    @review.restaurant = @restaurant
 #    if @review.save
 #    redirect_to restaurant_path(@restaurant)
 #    else
 #      render :new
 #    end

  #     private

  # def list_tip_params
  #   params.require(:tip).permit(:rating, :review, :category, :title, :address, :photo, :photo_cache, :lists)
  # end

  end

app/views/tips_lists/create.html.erb
<h1>TipsLists#create</h1>
<p>Find me in app/views/tips_lists/create.html.erb</p>

app/views/tips_lists/new.html.erb
<div class="web-container">
  <br>
  <h2 class="text-center">Create Tip</h2>
    <%= simple_form_for Tip.new, url: list_tips_lists_path do |c| %> <!-- this is the action that tells the button submit where to -->
      <div class="form-inputs col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
        Place <br>
        <input type= "text" class= "google-autocomplete" placeholder="Enter the place you wish to add"></input>
        <%= c.input :title, as: :hidden %>
        <%= c.input :address %>
        <%= c.input :category, label: 'Choose a category', collection: Tip::CATEGORIES %>
        <%= c.input :review, label: 'Your personal recommendation'%>
        <%= c.input :price_level, as: :hidden %>
        <%= c.input :google_pic, as: :hidden %>
        <%= c.input :photo, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
        <%= c.input :photo_cache, as: :hidden %>
        <%= image_tag "", width: 300, class: "hidden", id: "photo-preview" %>
        <div class="api-preview"></div>
        <div class="form-actions">
          <div class="d-flex justify-content-between align-items-center" style="margin-top: -30px">
            <%= link_to "Cancel", list_path(@list), class: "mr-5 ml-3"%>
            <%= c.button :submit, "SAVE", class: "add-button" %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/tips_lists/show.html.erb
<%= @list_tip.list.name %>

<%= @list_tip.tip.title %>