config/routes.rb
Rails.application.routes.draw do
  get 'tips_lists/new'
  get 'tips_lists/create'
  devise_for :users
  root to: 'pages#home'

  get "guests", to: "shares#index"
  get "guests/invite", to: "shares#new_guest"
  post "guests", to: "shares#invite_guest"
  get "guests/show", to: "shares#show"
  get "guests/share", to: "shares#share_list"
  get "guests/invite/url", to: "shares#invite_url"
  get "get_inspired", to: "tips#all_tips"
  get "get_inspired/new", to: "tips#add_to_list"


  resources :lists, only: [:index, :new, :create, :show] do
    resources :tips_lists, only: [:new, :create, :show]
  end

  resources :tips, only: [:new, :create]

  resources :tips, only: [:index, :show]
end

app/models/tip.rb
class Tip < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :list_tips
  mount_uploader :photo, PhotoUploader
  CATEGORIES = ["Bar", "Art Gallery", "Cafe", "Casino", "Museum", "Night Club", "Park", "Restaurant", "Attraction"]
  validates :category, inclusion: { in: CATEGORIES }
  COLORS = { "Bar": "turquoise", "Art Gallery": "pink", "Cafe": "beige", "Casino": "red", "Museum": "orange", "Night Club": "purple", "Park": "green", "Restaurant": "blue", "Attraction": "yellow" }
end

# update

app/controllers/tips_controller.rb
class TipsController < ApplicationController

  def new
    @tip = Tip.new
    @client = GooglePlaces::Client.new(ENV["GOOGLE_API"])

    @lists = current_user.lists.map { |instance| instance.name } # esta convirtiendo las instances en nada mas el nombre, con el fin de usarlos en el form select
    # (&:name)
    respond_to do |format|
      format.js {
        @place = params.keys.first
        @spot = @client.spots_by_query(@place).first
        @photo_url = @spot.photos[0].fetch_url(400)
      }
      format.html
    end
  end

  # See if list params is present
  # if list present create lists recommendations on form
  # if not just create tip without list
  def all_tips
    if params[:filter] == nil
      @tips = Tip.all
    else
      @tips = Tip.where(category: params[:filter])
    end
  end

  def add_to_list
    @tip = Tip.new
    @old_tip = Tip.find(params[:format])
    @lists = current_user.lists.map { |instance| instance.name }
  end

  def create
    if params[:old_tip].nil?
      @tip = Tip.new(tip_params)
      @tip.user = current_user
      list = List.find_by(name: params[:lists])
      if params[:lists].present?
        if @tip.save
          ListTip.create(tip_id: @tip.id, list_id: list.id)
            redirect_to tip_path(@tip) # redirecting to lists
        else
          render :new
        end
      else
        if @tip.save
          redirect_to tip_path(@tip) # redirecting to lists
        else
          render :new
        end
      end
    else
      @tip = Tip.find(params[:old_tip]).dup
      @tip.review = tip_params[:review]
      @tip.user_id = current_user.id
      list = List.find_by(name: params[:lists])
      if params[:lists].present?
        if @tip.save
          ListTip.create(tip_id: @tip.id, list_id: list.id)
            redirect_to get_inspired_path({tip: @tip.id, list: params[:lists]}) # redirecting to lists
        else
        end
      else
        if @tip.save
          redirect_to get_inspired_path(tip: @tip.id) # redirecting to lists
        else
        end
      end
    end
  end

  def index
    @tips = Tip.all
    @my_tips = Tip.where(user_id: current_user.id)
    @markers = @tips.map do |tip|
      {
        lat: tip.latitude,
        lng: tip.longitude
      }
    end
  end

  def show
    @tip = Tip.geocoded # returns Tip with coordinates
    @tip = Tip.find(params[:id])
    @markers = [{
      lat: @tip.latitude,
      lng: @tip.longitude
    }]
  end

  def edit
  end

  def update
  end

  def delete
  end

  private

  def tip_params
    params.require(:tip).permit(:rating, :review, :category, :title, :address, :photo, :photo_cache, :lists, :opening_hours, :price_level, :website, :google_pic)
  end
end

app/views/tips/add_to_list.html.erb
<div class="web-container">
  <br>
  <h2 class="text-center">Add Tip</h2>
    <%= simple_form_for(@tip) do |c| %> <!-- this is the action that tells the button submit where to -->
      <div class="form-inputs col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
        <%= c.input :title, input_html: {value: @old_tip.title}, label: 'Place', :readonly => true %>
        <%= c.input :address, input_html: {value: @old_tip.address}, :readonly => true %>
        <%= c.input :category, collection: Tip::CATEGORIES, selected: @old_tip.category, :readonly => true %>
        <%= c.input :review, label: 'Your personal recommendation' %>
        <input type="hidden" value="<%= @old_tip.id %>" name="old_tip">
        <%= c.input :price_level, as: :hidden, input_html: {value: @old_tip.price_level} %>
        List <br>
        <select name="lists" style="border-color: #CED4DA; background: white; width: 100%; padding: 7px; margin-bottom: 10px;">
          <option></option>
          <% @lists.each do |list| %>
            <option value="<%= list %>"><%= list.capitalize %></option>
          <% end %>
        </select>
        <%#= c.input :photo_cache,  as: :hidden %>
        <%#= c.input :photo, input_html: { class: 'd-none', id: 'photo-input', file: @old_tip.photo}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
        <% if @old_tip.photo.present? %>
          <%= cl_image_tag @old_tip.photo, width: 200, id: "photo-preview", height: 200 %>
        <%else%>
          <%= cl_image_tag @old_tip.google_pic, width: 200, id: "photo-preview", height: 200 %>
        <%end%>
        <div class="form-actions">
          <div class="d-flex justify-content-between align-items-center" style="margin-top: -30px">
            <%= link_to "Cancel", get_inspired_path, class: "mr-5 ml-3"%>
            <%= c.button :submit, "SAVE", class: "add-button" %>
          </div>
        </div>
    <% end %>
      </div>
</div>

app/views/tips/all_tips.html.erb
<div class="web-container">

<% if  params[:tip].present?%>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span> <strong>Congrats!</strong> <%= Tip.find(params[:tip]).title%> has been added to your <%= params[:list]%> list!</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

  <div class="title and subtitle">
    <h1 style="padding-top: 45px;">Get Inspired</h1>
    <br>
    <p id="p-centered">Add tips from other users to your lists</p>
  </div>
  <div class="button-container">
    <%= link_to "FILTER","", class:"add-button avatar dropdown-toggle" , id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Restaurant", get_inspired_path(filter: "Restaurant"), class: "dropdown-item" %>
          <%= link_to "Bar", get_inspired_path(filter: "Bar"), class: "dropdown-item" %>
          <%= link_to "Cafe", get_inspired_path(filter: "Cafe"), class: "dropdown-item" %>
          <%= link_to "Night Club", get_inspired_path(filter: "Night Club"), class: "dropdown-item" %>
          <%= link_to "Park", get_inspired_path(filter: "Park"), class: "dropdown-item" %>
          <%= link_to "Museum", get_inspired_path(filter: "Museum"), class: "dropdown-item" %>
          <%= link_to "Attraction", get_inspired_path(filter: "Attraction"), class: "dropdown-item" %>
          <%= link_to "Art Gallery", get_inspired_path(filter: "Art Gallery"), class: "dropdown-item" %>
          <%= link_to "Casino", get_inspired_path(filter: "Casino"), class: "dropdown-item" %>
          <%= link_to "All", get_inspired_path, class: "dropdown-item" %>
        </div>
  </div>

  <% # ["Bar", "Art Gallery", "Cafe", "Casino", "Museum", "Night Club", "Park", "Restaurant", "Attraction"] %>

  <% @tips.each do |tip| %>
    <div class="tips-index-links relative">
      <%= link_to "", get_inspired_new_path(tip), class:"absolute-0-0"%>
        <div class="d-flex justify-content-between align-items-center pt-3">
          <h2 class="mb-1">
          <%=  tip.title %>
          </h2>
        </div>
        <div class="list-card" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <% if tip.photo.present? %>
            <%= tip.photo %>
          <% else %>
            <%= tip.google_pic %>
          <%end%>); height: 200px; margin-top: 0px;">
          <btn class="pill-category-tips-index <%= Tip::COLORS[tip.category.to_sym] %>">
            <%= tip.category %>
          </btn>
          <div style="display: flex; justify-content: space-between; position: absolute; left: 0; bottom: 0; width: 100%; padding-right: 20px; padding-left: 20px;">
            <p>By: <%= User.find(tip.user_id).first_name %></p>
            <p id="plus"> <%= link_to "", get_inspired_new_path(tip), class:"fas fa-plus"%></p>
          </div>
        </div>
        <p class="address-tips-index mt-2" style="font-size: 16px">
          <%=  tip.address %>
        </p>
  <% end %>
    </div>
</div>

app/views/tips/edit.html.erb
<h1>Tips#edit</h1>
<p>Find me in app/views/tips/edit.html.erb</p>

app/views/tips/index.html.erb
<div class="web-container">
  <div class="d-flex justify-content-between">
      <%= link_to lists_path do %>

      <i class="fas fa-chevron-left" style="color: black; font-size: 1.3rem;"></i>

      <% end %>
    <i id="toogle-map-all-tips-index" class="fas fa-map-marked-alt" style="color: black; margin-top: 2px;"></i>
  </div>
  <br>
  <div>
    <h1>Your Tips</h1>
    <br>
  </div>
  <p id="p-centered">Add your favourite places</p>
  <div class="button-container">
    <%= link_to "CREATE TIP", new_tip_path, class:"add-button" %>
  </div>
  <div id="all-tips-index-cards">
    <% @my_tips.each do |my_tip| %>
      <div class="tips-index-links relative">
        <%= link_to "", tip_path(my_tip), class:"absolute-0-0"%>
          <div class="d-flex justify-content-between align-items-center mt-3 pt-3 mb-1">
            <h2 class="mb-2">
            <%=  my_tip.title %>
            </h2>
          </div>
          <div class="d-flex" style="margin-bottom: 12px;">
            <img class="avatar-show-page" alt="avatar-large" style="margin-top: 12px;"src="https://avatars2.githubusercontent.com/u/55089715?v=4" />
            <p class="list-card-review">
              <% if my_tip.review.length <= 83 %>
                <%=  my_tip.review[0, 83] %>
              <% else %>
                <%=  my_tip.review[0, 83] %> ...
              <% end %>
            </p>
          </div>
          <div class="list-card" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <% if my_tip.photo.present? %>
            <%= my_tip.photo %>
          <% else %>
            <%= my_tip.google_pic %>
          <%end%>); height: 200px;">
            <btn class="pill-category-tips-index <%= Tip::COLORS[my_tip.category.to_sym] %>">

              <%= my_tip.category %>
            </btn>
          </div>
          <p class="address-tips-index mt-2" style="font-size: 16px">
            <%=  my_tip.address %>
          </p>
      </div>
    <% end %>
  </div>
  <div id="location-div-all-tips-index" class="d-none">
    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/tips/new.html.erb
<div class="web-container">
  <br>
  <h2 class="text-center">Create Tip</h2>
    <%= simple_form_for(@tip) do |c| %> <!-- this is the action that tells the button submit where to -->
      <div class="form-inputs col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
        Place <br>
        <input type= "text" class= "google-autocomplete" placeholder="Enter the place you wish to add"></input>
        <%= c.input :title, as: :hidden %>
        <%= c.input :address %>
        <%= c.input :category, label: 'Choose a category', collection: Tip::CATEGORIES %>
        <%= c.input :review, label: 'Your personal recommendation' %>
        <%= c.input :price_level, as: :hidden %>
        <%= c.input :google_pic, as: :hidden %>
        List <br>
        <select name="lists" style="border-color: #CED4DA; background: white; width: 100%; padding: 7px; margin-bottom: 10px;">
          <option></option>
            <% @lists.each do |list| %>
              <option value="<%= list %>"><%= list.capitalize %></option>
            <% end %>
        </select>
        <%= c.input :photo_cache, as: :hidden %>
        <%= c.input :photo, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
        <%= image_tag "", width: 300, class: "hidden", id: "photo-preview" %>
        <div class="api-preview"></div>
        <div class="d-flex justify-content-between align-items-center" style="margin-top: -30px">
          <%= link_to "Cancel", tips_path, class: "mr-5 ml-3"%>
          <%= c.button :submit, "SAVE", class: "add-button" %>
        </div>
    <% end %>
      </div>

app/views/tips/new.js.erb
// console.log('<%= @spot %>')

var title = document.querySelector("#tip_title")
title.value = '<%= @spot.name %>'

var address = document.querySelector("#tip_address")
address.value = '<%= @spot.formatted_address %>'

var price_level = document.querySelector("#tip_price_level")
// console.log(price_level, '<%= @spot.price_level %>')
price_level.value = '<%= @spot.price_level %>'

var google_pic = document.querySelector("#tip_google_pic")
google_pic.value = '<%= @photo_url %>'


var google_pic = document.querySelector(".api-preview")
google_pic.style.backgroundImage = 'url(<%= @photo_url.gsub("\"", "") %>)'


// console.log(google_pic.value)

// console.log('<%= @spot.photos[0].photo_reference %>')
// console.log('<%=@photo_url%>')

// fetch(`https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=<%= @spot.photos[0].photo_reference %>&key=<%= ENV['GOOGLE_API']%>`)
//   .then(response => response.json())
//   .then((data) => {
//   console.log(data);})







// need to pull photo reference from api
// insert photo_reference into the fetch request

app/views/tips/show.html.erb
<div class="show-container">
  <div class="d-flex">
    <a href="#">
      <%= link_to tips_path do %><i class="fas fa-chevron-left" style="color: black; font-size: 1.3rem;"></i>
      <% end %>
    </a>
  </div>
    <div  >
      <h1 id="h1-show"> <%= @tip.title %></h1>
    </div>
      <p> <%= @tip.address %></p>
    <div id="avatar-and-comment" class="d-flex py-3">
      <!-- missing make the avatar dynamic, we need to ask the user to update a picture for that -->
      <img class="avatar-show-page" alt="avatar-large" src="https://avatars2.githubusercontent.com/u/55089715?v=4" />
      <p>"<%= @tip.review %>"</p>
    </div>
  <div id="show-info" >
    <div class="d-flex justify-content-end align-items-center" id= "photo-show-page" style="position: relative;">
      <% if @tip.photo.present? %>
        <%= cl_image_tag @tip.photo %>
      <% else %>
        <img alt="tip-photo" src= <%= @tip.google_pic %> />
      <% end %>
      <btn class="pill-category-show"> <%= @tip.category %> </btn>
    </div>
  </div>

<div id="location-div" class="d-none">
    <!-- <img src="https://images.pexels.com/photos/592753/pexels-photo-592753.jpeg?cs=srgb&dl=atlas-close-up-dark-dirty-592753.jpg&fm=jpg" alt="" height=100% width=100% style="border-radius: 8px;" > -->
    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>
  <br>
  <div class="">
    <p id="toogle-map-button" class="add-button-show-map">SHOW MAP</p>
  </div>
  <br>
  <br>
</div>